### 타행 계좌 이체 요청 : 유저 1
POST http://localhost:5000/acct/auth/b1
Authorization: {{Authorization1}}
Content-Type: application/json

{
  "bankCd": "001",
  "acctNo": "123123123"
}

### 타행 계좌 이체 요청 : 유저 2
POST http://localhost:5000/acct/auth/b1
Authorization: {{Authorization2}}
Content-Type: application/json

{
  "bankCd": "001",
  "acctNo": "123123123"
}

### 타행 계좌 이체 요청 : 유저 3
POST http://localhost:5000/acct/auth/b1
Authorization: {{Authorization3}}
Content-Type: application/json

{
  "bankCd": "001",
  "acctNo": "123123123"
}

### 타행 계좌 이체 요청 : 유저 4
POST http://localhost:5000/acct/auth/b1
Authorization: {{Authorization4}}
Content-Type: application/json

{
  "bankCd": "001",
  "acctNo": "123123123"
}

### 타행 계좌 이체 요청 : 유저 5
POST http://localhost:5000/acct/auth/b1
Authorization: {{Authorization5}}
Content-Type: application/json

{
  "bankCd": "001",
  "acctNo": "123123123"
}

###


