server.port: 5000
app:
 version: 0.1
 host: localhost:5000
spring:
 devtools:
   restart:
    enabled: true
   livereload:
    enabled: true
 flyway:
  enabled: false
  ignore-missing-migrations: true
  validate-on-migrate: true
  encoding: UTF-8
db:
 common:
  minIdle: 5
  maxPoolSize: 10
  idleTimeout: 10000
  dialect: org.hibernate.dialect.PostgreSQLDialect
 mybatis:
  common:
   driver-class-name: org.postgresql.Driver
   idleTimeout: 10000
  public:
   url: jdbc:postgresql://localhost:62501/postgres?ssl=false&charset=utf8
   user: postgres
   password: postgres
