app:
 vesion: 0.1
spring:
 devtools:
   restart:
    enabled: true
 flyway:
  enabled: false
  ignore-missing-migrations: true
  validate-on-migrate: true
  encoding: UTF-8
 datasource:
   initi-sql: "set time zone 'Asia/Seoul'"
db:
 common:
  minIdle: 5
  maxPoolSize: 10
  idleTimeout: 10000
  dialect: org.hibernate.dialect.PostgreSQLDialect
 mybatis:
  common:
   driver-class-name: org.postgresql.Driver
   idleTimeout: 10000
  public:
   url: jdbc:postgresql://localhost:62501/postgres?ssl=false&charset=utf8
   user: postgres
   password: postgres
